### ISSUE TITLE
refactor: Any chance to drop dependeny on SymPy?

### ISSUE THREAD

**Issue by rfzeg** [oKermorgant/slider_publisher#1]
https://github.com/oKermorgant/slider_publisher/blob/945919d46a9e0c06e73a57ecfd850c2ad71b8e59/slider_publisher#L49

I was trying out you package and I am wondering if there is a possibility to replace line 49 with code that is not dependent on SymPy. **Having to install SymPy to run your package imposes a hefty overhead that might not be required.**

I personally droped "eval_expr" and I seems to work well (but did not test extensively)
For instance:

```
def robust_eval(val):
    if type(val) in (list,tuple):
        return [robust_eval(v) for v in val]
    if type(val) == str:    # evaluate only if can be converted to float
        try:
            # out = float(eval_expr(val))
            out = float(val)
            return out
        except:
            return val
    return float(val)
```

**Comment by oKermorgant** [comment]
Hi, 

Thanks for pointing out this issue.
Indeed the sympy dependency is quite overkill. The only goal of this eval_expr was to be able to parse some `pi` fractions when written as hard-coded values in the Yaml files.
It has been removed in the last commit and replaced by a much simpler check.

**Comment by rfzeg** [comment]
Thanks for your quick response, I am so glad to hear that this was possible :)
All the best,

Roberto
